// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: modules/decs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_modules_decs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_modules_decs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Sent by the operator client for every action (insert command, list clients, resolve ID, etc.)
type CommandReqData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Guid          string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	CommandCode   int32                  `protobuf:"varint,3,opt,name=command_code,json=commandCode,proto3" json:"command_code,omitempty"`
	Param         string                 `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	Param2        string                 `protobuf:"bytes,5,opt,name=param2,proto3" json:"param2,omitempty"`
	CommandId     string                 `protobuf:"bytes,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	TaskedAt      string                 `protobuf:"bytes,7,opt,name=tasked_at,json=taskedAt,proto3" json:"tasked_at,omitempty"`
	Executed      int32                  `protobuf:"varint,8,opt,name=executed,proto3" json:"executed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReqData) Reset() {
	*x = CommandReqData{}
	mi := &file_modules_decs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReqData) ProtoMessage() {}

func (x *CommandReqData) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReqData.ProtoReflect.Descriptor instead.
func (*CommandReqData) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{2}
}

func (x *CommandReqData) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CommandReqData) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *CommandReqData) GetCommandCode() int32 {
	if x != nil {
		return x.CommandCode
	}
	return 0
}

func (x *CommandReqData) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *CommandReqData) GetParam2() string {
	if x != nil {
		return x.Param2
	}
	return ""
}

func (x *CommandReqData) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandReqData) GetTaskedAt() string {
	if x != nil {
		return x.TaskedAt
	}
	return ""
}

func (x *CommandReqData) GetExecuted() int32 {
	if x != nil {
		return x.Executed
	}
	return 0
}

// Generic success/failure reply
type CommandRespData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRespData) Reset() {
	*x = CommandRespData{}
	mi := &file_modules_decs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRespData) ProtoMessage() {}

func (x *CommandRespData) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRespData.ProtoReflect.Descriptor instead.
func (*CommandRespData) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{3}
}

func (x *CommandRespData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandRespData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeName      string                 `protobuf:"bytes,1,opt,name=code_name,json=codeName,proto3" json:"code_name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Pid           string                 `protobuf:"bytes,6,opt,name=pid,proto3" json:"pid,omitempty"`
	LastCheckin   string                 `protobuf:"bytes,7,opt,name=last_checkin,json=lastCheckin,proto3" json:"last_checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_modules_decs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *User) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *User) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *User) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *User) GetLastCheckin() string {
	if x != nil {
		return x.LastCheckin
	}
	return ""
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_modules_decs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{5}
}

func (x *UserDetails) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_modules_decs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_modules_decs_proto protoreflect.FileDescriptor

const file_modules_decs_proto_rawDesc = "" +
	"\n" +
	"\x12modules/decs.proto\x12\x02pb\"\x0e\n" +
	"\fEmptyRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xe5\x01\n" +
	"\x0eCommandReqData\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12!\n" +
	"\fcommand_code\x18\x03 \x01(\x05R\vcommandCode\x12\x14\n" +
	"\x05param\x18\x04 \x01(\tR\x05param\x12\x16\n" +
	"\x06param2\x18\x05 \x01(\tR\x06param2\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\tR\tcommandId\x12\x1b\n" +
	"\ttasked_at\x18\a \x01(\tR\btaskedAt\x12\x1a\n" +
	"\bexecuted\x18\b \x01(\x05R\bexecuted\"C\n" +
	"\x0fCommandRespData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xba\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tcode_name\x18\x01 \x01(\tR\bcodeName\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\tR\x03pid\x12!\n" +
	"\flast_checkin\x18\a \x01(\tR\vlastCheckin\"+\n" +
	"\vUserDetails\x12\x1c\n" +
	"\x04user\x18\x01 \x03(\v2\b.pb.UserR\x04user\"*\n" +
	"\x0fResolveResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xec\x01\n" +
	"\tMyService\x128\n" +
	"\vHealthCheck\x12\x10.pb.EmptyRequest\x1a\x17.pb.HealthCheckResponse\x128\n" +
	"\rInsertCommand\x12\x12.pb.CommandReqData\x1a\x13.pb.CommandRespData\x125\n" +
	"\x0eListClientsRPC\x12\x12.pb.CommandReqData\x1a\x0f.pb.UserDetails\x124\n" +
	"\tResolveID\x12\x12.pb.CommandReqData\x1a\x13.pb.ResolveResponseB\x10Z\x0erat/modules/pbb\x06proto3"

var (
	file_modules_decs_proto_rawDescOnce sync.Once
	file_modules_decs_proto_rawDescData []byte
)

func file_modules_decs_proto_rawDescGZIP() []byte {
	file_modules_decs_proto_rawDescOnce.Do(func() {
		file_modules_decs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_decs_proto_rawDesc), len(file_modules_decs_proto_rawDesc)))
	})
	return file_modules_decs_proto_rawDescData
}

var file_modules_decs_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_modules_decs_proto_goTypes = []any{
	(*EmptyRequest)(nil),        // 0: pb.EmptyRequest
	(*HealthCheckResponse)(nil), // 1: pb.HealthCheckResponse
	(*CommandReqData)(nil),      // 2: pb.CommandReqData
	(*CommandRespData)(nil),     // 3: pb.CommandRespData
	(*User)(nil),                // 4: pb.User
	(*UserDetails)(nil),         // 5: pb.UserDetails
	(*ResolveResponse)(nil),     // 6: pb.ResolveResponse
}
var file_modules_decs_proto_depIdxs = []int32{
	4, // 0: pb.UserDetails.user:type_name -> pb.User
	0, // 1: pb.MyService.HealthCheck:input_type -> pb.EmptyRequest
	2, // 2: pb.MyService.InsertCommand:input_type -> pb.CommandReqData
	2, // 3: pb.MyService.ListClientsRPC:input_type -> pb.CommandReqData
	2, // 4: pb.MyService.ResolveID:input_type -> pb.CommandReqData
	1, // 5: pb.MyService.HealthCheck:output_type -> pb.HealthCheckResponse
	3, // 6: pb.MyService.InsertCommand:output_type -> pb.CommandRespData
	5, // 7: pb.MyService.ListClientsRPC:output_type -> pb.UserDetails
	6, // 8: pb.MyService.ResolveID:output_type -> pb.ResolveResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_decs_proto_init() }
func file_modules_decs_proto_init() {
	if File_modules_decs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_decs_proto_rawDesc), len(file_modules_decs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_decs_proto_goTypes,
		DependencyIndexes: file_modules_decs_proto_depIdxs,
		MessageInfos:      file_modules_decs_proto_msgTypes,
	}.Build()
	File_modules_decs_proto = out.File
	file_modules_decs_proto_goTypes = nil
	file_modules_decs_proto_depIdxs = nil
}
