// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: decs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	C2Service_InsertIntoDatabase_FullMethodName = "/pb.C2Service/InsertIntoDatabase"
)

// C2ServiceClient is the client API for C2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type C2ServiceClient interface {
	InsertIntoDatabase(ctx context.Context, in *CommandReqData, opts ...grpc.CallOption) (*CommandRespData, error)
}

type c2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewC2ServiceClient(cc grpc.ClientConnInterface) C2ServiceClient {
	return &c2ServiceClient{cc}
}

func (c *c2ServiceClient) InsertIntoDatabase(ctx context.Context, in *CommandReqData, opts ...grpc.CallOption) (*CommandRespData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandRespData)
	err := c.cc.Invoke(ctx, C2Service_InsertIntoDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// C2ServiceServer is the server API for C2Service service.
// All implementations must embed UnimplementedC2ServiceServer
// for forward compatibility.
type C2ServiceServer interface {
	InsertIntoDatabase(context.Context, *CommandReqData) (*CommandRespData, error)
	mustEmbedUnimplementedC2ServiceServer()
}

// UnimplementedC2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedC2ServiceServer struct{}

func (UnimplementedC2ServiceServer) InsertIntoDatabase(context.Context, *CommandReqData) (*CommandRespData, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertIntoDatabase not implemented")
}
func (UnimplementedC2ServiceServer) mustEmbedUnimplementedC2ServiceServer() {}
func (UnimplementedC2ServiceServer) testEmbeddedByValue()                   {}

// UnsafeC2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to C2ServiceServer will
// result in compilation errors.
type UnsafeC2ServiceServer interface {
	mustEmbedUnimplementedC2ServiceServer()
}

func RegisterC2ServiceServer(s grpc.ServiceRegistrar, srv C2ServiceServer) {
	// If the following call panics, it indicates UnimplementedC2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&C2Service_ServiceDesc, srv)
}

func _C2Service_InsertIntoDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandReqData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2ServiceServer).InsertIntoDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2Service_InsertIntoDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2ServiceServer).InsertIntoDatabase(ctx, req.(*CommandReqData))
	}
	return interceptor(ctx, in, info, handler)
}

// C2Service_ServiceDesc is the grpc.ServiceDesc for C2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var C2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.C2Service",
	HandlerType: (*C2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertIntoDatabase",
			Handler:    _C2Service_InsertIntoDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "decs.proto",
}
