// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: modules/decs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandReqData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	CommandCode   int32                  `protobuf:"varint,2,opt,name=command_code,json=commandCode,proto3" json:"command_code,omitempty"`
	Param         string                 `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	Param2        string                 `protobuf:"bytes,4,opt,name=param2,proto3" json:"param2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReqData) Reset() {
	*x = CommandReqData{}
	mi := &file_modules_decs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReqData) ProtoMessage() {}

func (x *CommandReqData) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReqData.ProtoReflect.Descriptor instead.
func (*CommandReqData) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{0}
}

func (x *CommandReqData) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *CommandReqData) GetCommandCode() int32 {
	if x != nil {
		return x.CommandCode
	}
	return 0
}

func (x *CommandReqData) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *CommandReqData) GetParam2() string {
	if x != nil {
		return x.Param2
	}
	return ""
}

type CommandRespData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRespData) Reset() {
	*x = CommandRespData{}
	mi := &file_modules_decs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRespData) ProtoMessage() {}

func (x *CommandRespData) ProtoReflect() protoreflect.Message {
	mi := &file_modules_decs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRespData.ProtoReflect.Descriptor instead.
func (*CommandRespData) Descriptor() ([]byte, []int) {
	return file_modules_decs_proto_rawDescGZIP(), []int{1}
}

func (x *CommandRespData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandRespData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_modules_decs_proto protoreflect.FileDescriptor

const file_modules_decs_proto_rawDesc = "" +
	"\n" +
	"\x12modules/decs.proto\x12\x02pb\"u\n" +
	"\x0eCommandReqData\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12!\n" +
	"\fcommand_code\x18\x02 \x01(\x05R\vcommandCode\x12\x14\n" +
	"\x05param\x18\x03 \x01(\tR\x05param\x12\x16\n" +
	"\x06param2\x18\x04 \x01(\tR\x06param2\"C\n" +
	"\x0fCommandRespData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2J\n" +
	"\tC2Service\x12=\n" +
	"\x12InsertIntoDatabase\x12\x12.pb.CommandReqData\x1a\x13.pb.CommandRespDataB\fZ\n" +
	"modules/pbb\x06proto3"

var (
	file_modules_decs_proto_rawDescOnce sync.Once
	file_modules_decs_proto_rawDescData []byte
)

func file_modules_decs_proto_rawDescGZIP() []byte {
	file_modules_decs_proto_rawDescOnce.Do(func() {
		file_modules_decs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_decs_proto_rawDesc), len(file_modules_decs_proto_rawDesc)))
	})
	return file_modules_decs_proto_rawDescData
}

var file_modules_decs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_modules_decs_proto_goTypes = []any{
	(*CommandReqData)(nil),  // 0: pb.CommandReqData
	(*CommandRespData)(nil), // 1: pb.CommandRespData
}
var file_modules_decs_proto_depIdxs = []int32{
	0, // 0: pb.C2Service.InsertIntoDatabase:input_type -> pb.CommandReqData
	1, // 1: pb.C2Service.InsertIntoDatabase:output_type -> pb.CommandRespData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_decs_proto_init() }
func file_modules_decs_proto_init() {
	if File_modules_decs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_decs_proto_rawDesc), len(file_modules_decs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_decs_proto_goTypes,
		DependencyIndexes: file_modules_decs_proto_depIdxs,
		MessageInfos:      file_modules_decs_proto_msgTypes,
	}.Build()
	File_modules_decs_proto = out.File
	file_modules_decs_proto_goTypes = nil
	file_modules_decs_proto_depIdxs = nil
}
